`timescale 1ns/1ps

// Testbench for moving average module
// This uses randomly generated inputs/calculated outputs, and does not require any stimulus files generated by Matlab.
module bpm_detection_tb #(
    parameter DATA_IN_BITS = 17,
    parameter BPM_BITS = 11,
    parameter THRESHOLD = 70000,
    parameter MIN_PERIOD = 1181,
    parameter MAX_PERIOD = 1378
)();

    // DUT inputs/outputs
    logic clk;
    logic rst;
    logic data_in_ready;
    logic [DATA_IN_BITS - 1:0] data_in;
    logic data_out_ready;
    logic transient_out;
    logic [BPM_BITS - 1:0] bpm_out;

    // DUT
    bpm_detection #(
        .DATA_IN_BITS (DATA_IN_BITS),
        .BPM_BITS (BPM_BITS),
        .THRESHOLD (THRESHOLD),
        .MIN_PERIOD (MIN_PERIOD),
        .MAX_PERIOD (MAX_PERIOD)
    ) dut (
        .clk (clk),
        .rst (rst),
        .data_in_ready (data_in_ready),
        .data_in (data_in),
        .data_out_ready (data_out_ready),
        .transient_out (transient_out),
        .bpm_out (bpm_out)
    );

    // Clock generation (estimate 10ns clock)
    always begin
        clk = 1'b0;
        #5;
        clk = 1'b1;
        #5;
    end

    // Stimulus/testing logic
    string data_in_file;
    string bpm_out_file;
    string transient_out_file;
    string line;
    integer fd;

    logic [DATA_IN_BITS - 1:0] data_in_read;
    logic [BPM_BITS - 1:0] bpm_out_read;
    logic transient_out_read;
    logic [DATA_IN_BITS - 1:0] data_in_q [$];
    logic [BPM_BITS - 1:0] bpm_out_q [$];
    logic transient_out_q [$];
    logic [BPM_BITS - 1:0] bpm_out_expected;
    logic transient_out_expected;
    logic done;


    // Reset and load stimulus
    initial begin
        rst = 1'b1;
        done = 1'b0;
        data_in_ready = 1'b0;

        data_in_file = "blowyourmind_fir_filter.csv";
        bpm_out_file = "blowyourmind_bpm.csv";
        transient_out_file = "blowyourmind_transient.csv";
        
        fd = $fopen(data_in_file, "r");
        if (fd == 0) begin
            $display("Error: Could not open %s", data_in_file);
            $fatal;
        end
        while ($fgets(line, fd)) begin
            $sscanf(line, "%d", data_in_read);
            data_in_q.push_back(data_in_read);
        end
        $fclose(fd);

        fd = $fopen(transient_out_file, "r");
        if (fd == 0) begin
            $display("Error: Could not open %s", transient_out_file);
            $fatal;
        end
        while ($fgets(line, fd)) begin
            $sscanf(line, "%d", transient_out_read);
            transient_out_q.push_back(transient_out_read);
        end
        $fclose(fd);

        fd = $fopen(bpm_out_file, "r");
        if (fd == 0) begin
            $display("Error: Could not open %s", bpm_out_file);
            $fatal;
        end
        while ($fgets(line, fd)) begin
            $sscanf(line, "%d", bpm_out_read);
            bpm_out_q.push_back(bpm_out_read);
        end
        $fclose(fd);
        transient_out_expected <= 0;
        @(posedge clk);
        rst = 1'b0;
        bpm_out_expected <= MIN_PERIOD;
        $display("%t: Random stimulus generated.", $time);
        $display("%t: Data in loaded: %d samples.", $time, data_in_q.size());
        $display("%t: BPMs out loaded: %d samples.", $time, bpm_out_q.size());
        $display("%t: Thresholds out loaded: %d samples.", $time, transient_out_q.size());
        @(posedge clk);
        repeat (50) @(posedge clk);
        // Begin verification
        $display("%t: Beginning verification.", $time);
        @(posedge clk);
        data_in_ready <= 1'b1;
        @(posedge done);
        $display("%t: Test passed", $time);
        $finish;
    end

    always @(posedge clk) begin
        if (~rst) begin
            data_in_ready <= ~data_in_ready;
//            data_in_ready <= 1'b1;
        end
    end

    // Clocked DUT stimulus
    always @(negedge clk) begin
        if (data_in_ready) begin
            if (data_in_q.size > 0) begin
                data_in <= data_in_q.pop_front();
            end else begin
                data_in_ready <= 1'b0;
            end
        end
    end

    // Checker
    always @(posedge clk) begin
        if (data_out_ready) begin
            if (transient_out_q.size() > 0) begin
                transient_out_expected <= transient_out_q.pop_front;
                if (transient_out !== transient_out_expected) begin
                    $display("%t: Mismatch in transient: Expected %d, got %d", $time, transient_out_expected, transient_out);
                    // $fatal;
                end
            end else begin
                done <= 1'b1;
            end
            if (bpm_out_q.size() > 0) begin
                bpm_out_expected <= bpm_out_q.pop_front;
                if (bpm_out !== bpm_out_expected) begin
                    $display("%t: Mismatch in BPM out: Expected %d, got %d", $time, bpm_out_expected, bpm_out);
                    // $fatal;
                end
            end else begin
                done <= 1'b1;
            end
        end else begin
            transient_out_expected <= 1'b0;
        end
    end
    
    // 
endmodule