`timescale 1ns/1ps

// Testbench for moving average module
// This uses randomly generated inputs/calculated outputs, and does not require any stimulus files generated by Matlab.
module fir_filter_tb #(
    parameter DATA_IN_BITS = 17,
    parameter DATA_OUT_BITS = 17,
    parameter FILTER_BITS = 12,
    parameter FILTER_TAPS = 64,
    parameter COEFFICIENTS_FILE = "fir_filter_coefficients.mem"
)();

    // DUT inputs/outputs
    logic clk;
    logic rst;
    logic data_in_ready;
    logic [DATA_IN_BITS - 1:0] data_in;
    logic data_out_ready;
    logic [DATA_OUT_BITS - 1:0] data_out;

    // DUT
    fir_filter #(
        .DATA_IN_BITS (DATA_IN_BITS),
        .DATA_OUT_BITS (DATA_OUT_BITS),
        .FILTER_BITS (FILTER_BITS),
        .FILTER_TAPS (FILTER_TAPS),
        .COEFFICIENTS_FILE (COEFFICIENTS_FILE)
    ) dut (
        .clk (clk),
        .rst (rst),
        .data_in_ready (data_in_ready),
        .data_in (data_in),
        .data_out_ready (data_out_ready),
        .data_out (data_out)
    );

    // Clock generation (estimate 10ns clock)
    always begin
        clk = 1'b0;
        #5;
        clk = 1'b1;
        #5;
    end

    // Stimulus/testing logic
    string data_in_file;
    string data_out_file;
    string line;
    integer fd;

    logic [DATA_IN_BITS - 1:0] data_in_read;
    logic [DATA_OUT_BITS - 1:0] data_out_read;
    logic [DATA_IN_BITS - 1:0] data_in_q [$];
    logic [DATA_OUT_BITS - 1:0] data_out_q [$];
    logic [DATA_OUT_BITS - 1:0] data_out_expected;

    logic done;


    // Reset and load stimulus
    initial begin
        rst = 1'b1;
        done = 1'b0;
        data_in_ready = 1'b0;

        data_in_file = "blowyourmind_moving_average.csv";
        data_out_file = "blowyourmind_fir_filter.csv";

        fd = $fopen(data_in_file, "r");
        if (fd == 0) begin
            $display("Error: Could not open %s", data_in_file);
            $fatal;
        end
        while ($fgets(line, fd)) begin
            $sscanf(line, "%d", data_in_read);
            data_in_q.push_back(data_in_read);
        end
        $fclose(fd);

        fd = $fopen(data_out_file, "r");
        if (fd == 0) begin
            $display("Error: Could not open %s", data_out_file);
            $fatal;
        end
        while ($fgets(line, fd)) begin
            $sscanf(line, "%d", data_out_read);
            data_out_q.push_back(data_out_read);
        end
        $fclose(fd);

        
        @(posedge clk);
        $display("%t: Data in loaded: %d samples.", $time, data_in_q.size());
        $display("%t: Data out loaded: %d samples.", $time, data_out_q.size());
        @(negedge clk);
        rst = 1'b0;
        data_out_expected <= 0;
        // Begin verification
        $display("%t: Beginning verification.", $time);
        @(posedge done);
        $display("%t: Test passed", $time);
        $finish;
    end

    always @(posedge clk) begin
        if (~rst) begin
            data_in_ready <= ~data_in_ready;
            // data_in_ready <= 1'b1;
        end
    end

    // Clocked DUT stimulus
    always @(negedge clk) begin
        if (data_in_ready) begin
            if (data_in_q.size > 0) begin
                data_in <= data_in_q.pop_front();
            end else begin
                data_in_ready <= 1'b0;
            end
        end
    end

    // Checker
    always @(posedge clk) begin
        if (data_out_ready) begin
            if (data_out_q.size() > 0) begin
                data_out_expected <= data_out_q.pop_front;
                if (data_out !== data_out_expected) begin
                    $display("%t: Mismatch in data out: Expected %d, got %d", $time, data_out_expected, data_out);
                        $fatal;
                end
            end else begin
                done <= 1'b1;
            end
        end
    end
    
    // 
endmodule